### ISSUE TITLE
Parse VNF package with multiple deployment flavors 

### ISSUE THREAD

**Issue by Cbkhare** [RIFTIO/tosca-parser#3]
Hi,

I am looking forward for a way to create set of deployment flavor from a VNF package. **ETSI SOL001 v. 2.6.1 Annex A** describes the main design principle for VNF deployment flavor and the mapping between VNF deployment flavor elements to TOSCA types. 

ETSI SOL001 version 2.6.1 (in Annex A, page no.170, under section A.1.2) describes that a deployment flavor is "standalone implementable TOSCA service template". 

Further in section A.2 page no.171 via an example it explains how an abstract node of type tosca.nodes.nfv.VNF will be a top level resource, and will **import** set of low level resource (a deployment flavor) described in individual service template. 

Does tosca-parser have a mechanism to identify the deployment flavor or low level resource which a service template of Top level resource imports and extract their properties ? 

attached a copy of ETSI SOL001 2.6.1

[gs_NFV-SOL001v020601.pdf](https://github.com/RIFTIO/tosca-parser/files/4015837/gs_NFV-SOL001v020601.pdf)

**Comment by jphilip09** [comment]
Hi,

> 
> Does tosca-parser have a mechanism to identify the deployment flavor or low level resource which a service template of Top level resource imports and extract their properties ?
> 

The parser only parses the input files, validates that it follows the specs and provides a dictionary of the various constructs. It has no mechanism to map the abstract node definition to low level resource or actual VNF.  For mapping the abstract node to a VNF descriptor based on the node type, properties and interfaces, you will need a VNFM/NFV orchestrator. The flavor id is specified during instantiation and is then used to instantiate the VNF.

Regards,
Philip
